config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :category do
  	  resources :tintuc, show: [:only] 
  	  resources :subcategory, show: [:only]
    end
    
    resources :category do
  	  resources :subcategory, show: [:only]
    end
    
     resources :subcategory do
        resources :post, show: [:only]
      end
      
      resources :tintuc
      resources :post
    
    get "/sitemap" => "post#sitemap", format: :xml, as: :sitemap
    
    root "category#index"
   
    get '/news' => 'category#news'
    get '/video' => 'category#video'
    get '/tuvung' => 'category#tuvung'
    get '/trochoi' => 'category#trochoi'
    get '/baihat' => 'category#baihat'
    get '/nguphap' => 'category#nguphap'
   
    

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :tintucs
    has_many :subcategories
    extend FriendlyId
	friendly_id :slug, use: [:slugged, :finders]
    
    has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    
     has_attached_file :logo, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :subcategory
  
  extend FriendlyId
	friendly_id :slug, use: [:slugged, :finders]
  
    has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    has_attached_file :socialshare, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :socialshare, :content_type => /\Aimage\/.*\Z/
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
    belongs_to :category
    has_many :posts
    extend FriendlyId
	friendly_id :slug, use: [:slugged, :finders]
    
    has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    
     has_attached_file :logo, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/tintuc.rb
class Tintuc < ActiveRecord::Base
    belongs_to :category
    
    extend FriendlyId
	friendly_id :slug, use: [:slugged, :finders]
	
	validates :title, presence: true, length: { maximum: 80 }
   
    has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    has_attached_file :socialshare, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :socialshare, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  validates :name, presence: true, length: {maximum: 25}

  def self.find_for_google_oauth2(access_token, signed_in_resourse=nil)
  	data = access_token.info
  	user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

  	if user
  		return user
  	else
  		registered_user = User.where(:email => access_token.email).first
  		if registered_user
  			return registered_user
  		else
  			user = User.create(
  				name: data["name"],
  				provider: access_token.provider,
  				email: data["email"],
  				uid: access_token.uid,
          image: data["image"],
  				password: Devise.friendly_token[0,20],
  			)
  		end
  	end
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resourse=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

    if user
      return user
    else
      registered_user = User.where(:email => data.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
          name: access_token.extra.raw_info.name,
          provider: access_token.provider,
          email: data.email,
          uid: access_token.uid,
          image: data.image,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all.order(:tag)
    @subcategories = Subcategory.all
    @tintucs = Tintuc.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @tintucs = @category.tintucs
    @category = Category.find(params[:id])
    @subcategories = @category.subcategories
  end
  
  def video
    @categories = Category.all
    @tintucs = Tintuc.all
    @subcategories = Subcategory.all
  end
  
  def news
    @categories = Category.all
    @subcategories = Subcategory.all
    @tintucs = Tintuc.all
  end
  
  def tuvung
    @categories = Category.all
    @subcategories = Subcategory.all
    @tintucs = Tintuc.all
  end
  
  def trochoi
    @categories = Category.all
    @subcategories = Subcategory.all
    @tintucs = Tintuc.all
  end
  
  def baihat
    @categories = Category.all
    @subcategories = Subcategory.all
    @tintucs = Tintuc.all
  end
  
  def nguphap
    @categories = Category.all
    @subcategories = Subcategory.all.order(:tag)
    @tintucs = Tintuc.all
  end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def show
    subcategory = Subcategory.find(params[:subcategory_id])
  	@post = Post.find(params[:id])
  	@posts = subcategory.posts.order(:tag).page(params[:page]).per(7)
  	@categories = Category.all
  end

  def sitemap
    @posts = Post.all
  end
end

app/controllers/subcategory_controller.rb
class SubcategoryController < ApplicationController
  def show
    @subcategory = Subcategory.all
    @category = Category.find(params[:category_id])
    @subcategory = Subcategory.find(params[:id])
  	@posts = @subcategory.posts.order(:tag)
  	@categories = Category.all
  end

end

app/controllers/tintuc_controller.rb
class TintucController < ApplicationController
  def show
    category = Category.find(params[:category_id])
    @tintuc = Tintuc.find(params[:id])
    @tintucs = category.tintucs.order(created_at: :desc).page(params[:page]).per(9)
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		if user.image
			user.image
		else 
			"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=50"
		end
	end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/tintuc_helper.rb
module TintucHelper
end

app/views/category/baihat.html.erb
<% content_for :head do %>
	<title>Chapry.com</title>
	<!-- Open Graph data -->
	<meta property="og:site_name" content="chapry">
	<meta property="fb:app_id" content="984512708308216"></meta>
	<meta property="og:url" content="<%= request.original_url %>"></meta>
	<meta property="og:type" content="article">
	<meta property="og:title" content="chapry.com | Học Tiếng Anh The Fun Way">
	<meta property="og:description" content="Video Clip, Tin Tức, Trò Chơi, Bài Hát">
	<meta property="og:image" content="https://s3-ap-southeast-1.amazonaws.com/chaprycms/logo1">
<% end %>

<%= render partial: "shared/header" %>

<!-- DESKTOP -->
<!-- TOP AD DESKTOP-->
<div class="w3-dark-grey w3-hide-medium w3-hide-small w3-main">
	<div style="max-width:1260px;margin:auto" class="w3-container">
		<div style="margin-left:50px;margin-bottom:10px">
			<img src="https://s3-ap-southeast-1.amazonaws.com/chaprycms/Google+Adsense/add+5.png"  style="">	
		</div>
	</div>
</div>
<!-- CATEGORY TABS DESKTOP-->
<div style="font-family: 'Raleway', sans-serif" class="cartab w3-black w3-hide-medium w3-hide-small w3-container">
	<div style="max-width:1260px;margin:auto" class="w3-conntainer">
        <div style="margin-left:20px">
        	<%= link_to "Từ Vựng", root_path, class: "w3-hover-blue w3-padding  w3-btn" %>
        	
        	<%= link_to "Luyện Nghe", video_path, class: "w3-hover-blue w3-padding w3-btn" %>
        	
        	<%= link_to "Luyện Nói", news_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<!--<%= link_to "Luyện Nghe", tuvung_path, class: "w3-hover-blue w3-padding w3-btn" %>-->
        		
        	<%= link_to "Bài Hát", trochoi_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<%= link_to "Giải trí", baihat_path, class: "w3-hover-blue w3-padding w3-btn" %>
    
        	<%= link_to "Phát Âm", nguphap_path, class: "w3-hover-blue w3-padding w3-btn" %>
        </div>	
    </div>	
</div>

<!-- A DESKTOP-->
<div style="max-width:600px;margin:auto" class="w3-container w3-hide-medium w3-hide-small w3-animate-opacity">
  <% @tintucs.each do |tintuc| %>
	  <% if tintuc.musica %>
		  <%= link_to [tintuc.category, tintuc] do %>
		  	<div class="w3-contaner">
				<div class="w3-display-container">
					<%= image_tag tintuc.image.url, style: "width:100%" %>
				    <div style="font-family: 'Raleway', sans-serif;font-size:1.2rem;line-height:1.2;color:white" class="w3-hover-opacity w3-blue w3-padding w3-display-bottomleft">
				    	<p><%= tintuc.title %></p>
				    </div>
				</div>	
			</div>
		  <% end %>
	  <% end %>
  <% end %>
</div>

<!-- FACEBOOK LIKE-->
<div class="w3-margin-top w3-hide-medium w3-hide-small w3-container">
	<div style="max-width:1260px;margin:auto" class="w3-main" >
		<div style="margin-left:50px" class="w3-container">
			<div style="" class="w3-container">
				<div class="fb-page" data-href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" data-tabs="timeline" data-width="180" data-height="70" data-small-header="true" data-adapt-container-width="false" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/"></a></blockquote></div>Kết Nối Vối Chapry trên Facebook
			</div>	
		</div>	
	</div>	
</div>

<!-- B DESKTOP-->
<div style="max-width:1260px;margin:auto" class="w3-hide-medium w3-hide-small w3-main" >
	<div style="margin-left:50px" class="w3-container">
		<% @tintucs.each do |tintuc| %>
			<% if tintuc.musicb %>
				<%= link_to [tintuc.category, tintuc] do %>
					<div class="w3-col l2">
						<div class="w3-margin-right content">
							<div class="w3-display-container">
								<%= image_tag tintuc.image.url, style: "width:100%" %>
							</div>
							<div style="min-height:150px;line-height:1.2;font-size:14px" class="w3-container">
			  					<p style="margin-bottom:-10px!important;color:#9E8383;font-size:10px!important"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(tintuc.created_at)%> ago </p>
			  					<p><%= tintuc.title %></p>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>



<!-- IPAD-->
<!-- TOP AD IPAD -->
<div class="w3-dark-grey w3-hide-large w3-hide-small w3-main">
	<div style="margin-left:50px">
		<img src="https://s3-ap-southeast-1.amazonaws.com/chaprycms/Google+Adsense/add+6.png"  style="width:100%">	
	</div>
</div>

<!-- CATEGORY TABS IPAD-->
<div style="font-family: 'Raleway', sans-serif" class="cartab w3-black w3-hide-small w3-hide-large w3-container">
	<div style="max-width:1260px;margin:auto" class="w3-margin-left w3-conntainer">
        <div>
        	<%= link_to "Từ Vựng", root_path, class: "w3-hover-blue w3-padding  w3-btn" %>
        	
        	<%= link_to "Luyện Nghe", video_path, class: "w3-hover-blue w3-padding w3-btn" %>
        	
        	<%= link_to "Luyện Nói", news_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<!--<%= link_to "Luyện Nghe", tuvung_path, class: "w3-hover-blue w3-padding w3-btn" %>-->
        		
        	<%= link_to "Bài Hát", trochoi_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<%= link_to "Giải trí", baihat_path, class: "w3-hover-blue w3-padding w3-btn" %>
    
        	<%= link_to "Phát Âm", nguphap_path, class: "w3-hover-blue w3-padding w3-btn" %>
        </div>	
    </div>	
</div>
	
<!-- A IPAD -->
<div class="w3-margin-left w3-hide-large w3-hide-small w3-black w3-container">
	<div class="w3-container w3-hide-large w3-hide-small w3-animate-opacity">
	  <% @tintucs.each do |tintuc| %>
		  <% if tintuc.musica %>
		  <%= link_to [tintuc.category, tintuc] do %>
		  	<div class="w3-col m12 ">
				<div class="w3-display-container">
					<%= image_tag tintuc.image.url, style: "width:100%" %>
				    <div style="font-family: 'Raleway', sans-serif;font-size:1.2rem;line-height:1.2;color:white" class="w3-blue w3-hover-opacity w3-padding w3-display-bottomleft">
				    	<p><%=  tintuc.title %></p>
				    </div>
				</div>	
			</div>
		  <% end %>
		  <% end %>
	  <% end %>
	</div>
</div>	

<!-- FACEBOOK LIKE IPAD -->
<div class="w3-margin-top w3-margin-left w3-hide-large w3-hide-small w3-container">
	<div style="max-width:1260px;margin:auto" class="w3-main" >
		<div class="w3-container">
			<div style="" class="w3-container">
				<div class="fb-page" data-href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" data-tabs="timeline" data-width="180" data-height="70" data-small-header="true" data-adapt-container-width="false" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/"></a></blockquote></div>Kết Nối Vối Chapry trên Facebook
			</div>	
		</div>	
	</div>	
</div>

<!-- B IPAD -->
<div class="w3-margin-left w3-hide-large w3-hide-small w3-container">
	<% @tintucs.each do |tintuc| %>
		<% if tintuc.musicb %>
		<%= link_to [tintuc.category, tintuc] do %>
			<div class="w3-col m3">
				<div class="w3-white w3-margin-right content">
					<div class=" w3-display-container">
						<%= image_tag tintuc.image.url, style: "width:100%" %>
					</div>
					<div style="min-height:150px;line-height:1.2;font-size:14px" class="w3-container">
	  					<p style="margin-bottom:-10px!important;color:#9E8383;font-size:10px!important"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(tintuc.created_at)%> ago </p>
	  					<p><%= tintuc.title %></p>
					</div>
				</div>
			</div>
		<% end %>
		<% end %>
	<% end %>
</div>


<!-- PHONE -->

<!-- CATEGORY TABS IPAD-->
<div style="margin-top:50px;font-family: 'Raleway', sans-serif" class="cartab w3-black w3-hide-medium w3-hide-large w3-container">
	<div  class=" w3-container">
        	<%= link_to "Từ Vựng", root_path, class: "w3-hover-blue w3-padding  w3-btn" %>
        	
        	<%= link_to "Luyện Nghe", video_path, class: "w3-hover-blue w3-padding w3-btn" %>
        	
        	<%= link_to "Luyện Nói", news_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<!--<%= link_to "Luyện Nghe", tuvung_path, class: "w3-hover-blue w3-padding w3-btn" %>-->
        		
        	<%= link_to "Bài Hát", trochoi_path, class: "w3-hover-blue w3-padding w3-btn" %>
        		
        	<%= link_to "Giải trí", baihat_path, class: "w3-hover-blue w3-padding w3-btn" %>
    
        	<%= link_to "Phát Âm", nguphap_path, class: "w3-hover-blue w3-padding w3-btn" %>
    </div>	
</div>

<!-- A IPAD -->
<div class="w3-hide-large w3-hide-medium w3-black w3-container">
	<div class="w3-container w3-hide-large w3-hide-medium w3-animate-opacity">
	  <% @tintucs.each do |tintuc| %>
		  <% if tintuc.musica %>
		  <%= link_to [tintuc.category, tintuc] do %>
		  	<div class="w3-col m12 ">
				<div class="w3-display-container">
					<%= image_tag tintuc.image.url, style: "width:100%" %>
				    <div style="font-family: 'Raleway', sans-serif;font-size:1.2rem;line-height:1.2;color:white" class="w3-blue w3-hover-opacity w3-padding w3-display-bottomleft">
				    	<p><%=  tintuc.title %></p>
				    </div>
				</div>	
			</div>
		  <% end %>
		  <% end %>
	  <% end %>
	</div>
</div>
<!-- FACEBOOK LIKE PHONE-->
<div class="w3-margin-top  w3-hide-large w3-hide-medium w3-container">
	<div style="max-width:1260px;margin:auto" class="w3-main" >
		<div class="w3-container">
			<div style="" class=" w3-container">
				<div class="fb-page" data-href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" data-tabs="timeline" data-width="180" data-height="70" data-small-header="true" data-adapt-container-width="false" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Nh%E1%BA%ADt-K%C3%BD-H%E1%BB%8Dc-Ti%E1%BA%BFng-Anh-143868439376052/"></a></blockquote></div>Kết Nối Vối Chapry trên Facebook
			</div>	
		</div>	
	</div>	
</div>

<!-- B PHONE-->
<div class="w3-hide-medium w3-hide-large w3-container">
	<% @tintucs.each do |tintuc| %>
		<% if tintuc.musicb %>
		<%= link_to [tintuc.category, tintuc] do %>
			<div class="w3-col w3-padding-small s6">
				<div class="w3-container">
					<%= image_tag tintuc.image.url, style: "width:100%" %>
					<div style="min-height:60px;line-height:1.2;font-size:14px" class="w3-container">
	  					<p style="margin-bottom:-10px!important;color:#9E8383;font-size:10px!important"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(tintuc.created_at)%> ago </p>
	  					<p><%= tintuc.title %></p>
					</div>
				</div>
			</div>
		<% end %>
		<% end %>
	<% end %>
</div>
<%= render partial: "shared/footer" %>

<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
  <meta property="fb:pages" content="290275247971028" />
  <link rel="icon" href="https://s3-ap-southeast-1.amazonaws.com/chaprycms/websiite+logo/32x32" sizes="32x32">
  <link rel="icon" href="https://s3-ap-southeast-1.amazonaws.com/chaprycms/websiite+logo/196x196" sizes="196x196">
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-77380258-1', 'auto');
  ga('send', 'pageview');
</script> 
</head>
<body>

<%= yield %>

<script>
function w3_open() {
    document.getElementsByClassName("w3-sidenav")[0].style.width = "100%";
    document.getElementsByClassName("w3-sidenav")[0].style.display = "block";
}
function w3_close() {
    document.getElementsByClassName("w3-sidenav")[0].style.display = "none";
}
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=157760634616271";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>
function myFunction() {
    var x = document.getElementById("Demo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else { 
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

app/views/shared/_categorytab.html.erb
<div style="font-family: 'Raleway', sans-serif;margin-left:50px" class="cartab w3-center w3-hide-medium w3-hide-small w3-container">
	<%= link_to "Home", root_path, class: "w3-dark-grey w3-btn" %>
	
	<%= link_to "Video", video_path, class: "w3-dark-grey w3-btn" %>
	
	<%= link_to "Tin Tức", news_path, class: "w3-dark-grey w3-btn" %> 
		
	<%= link_to "Học Tiếng Anh", tuvung_path, class: "w3-dark-grey w3-btn" %>
		
	<!--<%= link_to "Trò Chơi", trochoi_path, class: "w3-dark-grey w3-btn" %>
		
	<%= link_to "Âm Nhạc", baihat_path, class: "w3-dark-grey w3-btn" %>
		
	<%= link_to "Ngữ Pháp", nguphap_path, class: "w3-dark-grey w3-btn" %>-->
</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="w3-container w3-center w3-padding-large w3-black">
	 <p><strong>Follow Us</strong></p>
	 <a style="background:#A8182F" class="w3-btn-floating" href="https://www.facebook.com/chaprynz/" title="Facebook"><i class="fa fa-facebook"></i></a>
  
      <a style="background:#A8182F" class="w3-btn-floating" href="https://plus.google.com/u/1/118075415996247592824?hl=en" title="Google +"><i class="fa fa-google-plus"></i></a>
     <p style="color:#A8182F"><strong>Contact: chaprynz@chapry.com</strong></p>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_search.html.erb
<li class="w3-hide-small" style="max-width:360px"><script>
  (function() {
    var cx = '016268021366694860448:xuuskjzcad8';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search></li>